server:
  port: 9000
  tomcat:
    uri-encoding: UTF-8

spring:
  application:
    name: base-service
  profiles:
    active: dev
  cloud:
    config:
      discovery:
        serviceId: config-server
        enabled: true
      label: master
      profile: dev

base.worker.id: 1
base.data.center.id: 1